### ISSUE TITLE
Install dev_requirements by default

### ISSUE THREAD

**Issue by amercer1** [iPlantCollaborativeOpenSource/clank#74]
If jenkins is not set to TRUE, then dev_requirements is not installed. Apparently it should be anyways.

**Comment by lenards** [comment]
I triaged this briefly while working on Clank v2.0 + Vagrant... 

Adding some notes here 📓 (they may not be overly helpful or they might be just plain obvious - sorry in advance)
- - - 
This is because the requirements passed to [roles/app-pip-install-requirements](https://github.com/iPlantCollaborativeOpenSource/clank/blob/master/roles/app-pip-install-requirements/tasks/main.yml) is set to [just `'requirements.txt'`](https://github.com/iPlantCollaborativeOpenSource/clank/blob/master/roles/app-pip-install-requirements/tasks/main.yml#L6) in the _included_ `setup_*` playbooks.

A quick or immediate fix would be to alter: 

https://github.com/iPlantCollaborativeOpenSource/clank/blob/master/playbooks/setup_atmosphere.yml#L21-L27

**Comment by lenards** [comment]
The reason [`setup_troposphere.yml`](https://github.com/iPlantCollaborativeOpenSource/clank/blob/master/playbooks/setup_troposphere.yml#L18-L21) does **not** have this issue is because the task for `pip install ...` did a `dev_requirements.txt` previously. I carried this distinction over from `atmosphere-setup-atmosphere` when porting. 

So troposphere's usage leverage the default [`REQUIREMENTS_FILE_NAME`](https://github.com/iPlantCollaborativeOpenSource/clank/blob/master/roles/app-pip-install-requirements/vars/main.yml#L8) defined in `vars` but used in `defaults`.

**Comment by amercer1** [comment]
This issue was addressed in PR [86](https://github.com/iPlantCollaborativeOpenSource/clank/pull/86).
